USE [QlySach]
GO
/****** Object:  Table [dbo].[LOAI]    Script Date: 1/5/2021 9:58:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOAI](
	[MALOAI] [varchar](10) NOT NULL,
	[LOAI] [nvarchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MALOAI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SACH]    Script Date: 1/5/2021 9:58:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SACH](
	[TENSACH] [nvarchar](40) NOT NULL,
	[MATACGIA] [varchar](10) NULL,
	[LOAI] [varchar](10) NULL,
	[HINHANH] [nvarchar](70) NULL,
	[GIATIEN] [int] NULL,
	[SOLUONG] [int] NULL,
	[CONGTY] [nvarchar](50) NULL,
	[NXB] [nchar](10) NULL,
	[KICHTHUOC] [nvarchar](20) NULL,
	[LOAIBIA] [nvarchar](50) NULL,
	[SOTRANG] [int] NULL,
	[SKU] [nvarchar](100) NULL,
	[NGAYXB] [date] NULL,
	[MOTA] [nvarchar](200) NULL,
 CONSTRAINT [PK__SACH__B7E5A0C2D76D8180] PRIMARY KEY CLUSTERED 
(
	[TENSACH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TACGIA]    Script Date: 1/5/2021 9:58:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TACGIA](
	[MATG] [varchar](10) NOT NULL,
	[TEN] [nvarchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MATG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[LOAI] ([MALOAI], [LOAI]) VALUES (N'KH', N'Khoa Học')
GO
INSERT [dbo].[LOAI] ([MALOAI], [LOAI]) VALUES (N'NA', N'Nấu Ăn')
GO
INSERT [dbo].[LOAI] ([MALOAI], [LOAI]) VALUES (N'TrT', N'Trữ Tình')
GO
INSERT [dbo].[LOAI] ([MALOAI], [LOAI]) VALUES (N'TrTr', N'Truyện Tranh')
GO
INSERT [dbo].[LOAI] ([MALOAI], [LOAI]) VALUES (N'TTh', N'Tiểu Thuyết')
GO
INSERT [dbo].[SACH] ([TENSACH], [MATACGIA], [LOAI], [HINHANH], [GIATIEN], [SOLUONG], [CONGTY], [NXB], [KICHTHUOC], [LOAIBIA], [SOTRANG], [SKU], [NGAYXB], [MOTA]) VALUES (N'TONYBUOITOI', N'ND', N'TrTr', NULL, 200000, 100, NULL, N'KIMDONG   ', N'25X30', NULL, 563, N'AAABBBBCCC', NULL, N'HOC HOI KIEN THUC')
GO
INSERT [dbo].[SACH] ([TENSACH], [MATACGIA], [LOAI], [HINHANH], [GIATIEN], [SOLUONG], [CONGTY], [NXB], [KICHTHUOC], [LOAIBIA], [SOTRANG], [SKU], [NGAYXB], [MOTA]) VALUES (N'TONYBUOITRUA', N'TH', N'TrT', NULL, 200000, 100, NULL, N'KIMDONG   ', N'25X30', NULL, 200, N'AAABBBBCCC', NULL, N'HOC HOI KIEN THUC')
GO
INSERT [dbo].[SACH] ([TENSACH], [MATACGIA], [LOAI], [HINHANH], [GIATIEN], [SOLUONG], [CONGTY], [NXB], [KICHTHUOC], [LOAIBIA], [SOTRANG], [SKU], [NGAYXB], [MOTA]) VALUES (N'TONYNUADEM', N'TT', N'KH', NULL, 200000, 100, NULL, N'KIMDONG   ', N'25X30', NULL, 236, N'AAABBBBCCD', NULL, N'HOC HOI KIEN THUC')
GO
INSERT [dbo].[TACGIA] ([MATG], [TEN]) VALUES (N'NC', N'Nam Cao')
GO
INSERT [dbo].[TACGIA] ([MATG], [TEN]) VALUES (N'ND', N'Nguyễn Du')
GO
INSERT [dbo].[TACGIA] ([MATG], [TEN]) VALUES (N'TH', N'Tố Hữu')
GO
INSERT [dbo].[TACGIA] ([MATG], [TEN]) VALUES (N'TT', N'Tất Tố')
GO
ALTER TABLE [dbo].[SACH]  WITH CHECK ADD  CONSTRAINT [FK__SACH__LOAI__4D94879B] FOREIGN KEY([LOAI])
REFERENCES [dbo].[LOAI] ([MALOAI])
GO
ALTER TABLE [dbo].[SACH] CHECK CONSTRAINT [FK__SACH__LOAI__4D94879B]
GO
ALTER TABLE [dbo].[SACH]  WITH CHECK ADD  CONSTRAINT [FK__SACH__MATACGIA__4CA06362] FOREIGN KEY([MATACGIA])
REFERENCES [dbo].[TACGIA] ([MATG])
GO
ALTER TABLE [dbo].[SACH] CHECK CONSTRAINT [FK__SACH__MATACGIA__4CA06362]
GO
USE [master]
GO
ALTER DATABASE [QlySach] SET  READ_WRITE 
GO
